### ISSUE TITLE
Bullets not rendering ok Kakoune getting started

### ISSUE THREAD

**Issue by sidkshatriya** [erlang-ls/erlang-ls.github.io#65]
I was looking at https://erlang-ls.github.io/getting-started/kakoune/ and I notice that the bullets were not rendering.

![Kakoune - Erlang LS](https://user-images.githubusercontent.com/638477/139395592-d80274cc-8912-4c07-8b0d-8c3591b8de04.png)

There are many flavors of markdown. I was wondering if the bullets did not render because I used `-` instead of `*`. Interestingly if you see https://github.com/erlang-ls/erlang-ls.github.io/blob/mkdocs/docs/getting-started/kakoune.md the bullets render.

I'll be happy to submit a PR if I've correctly diagnosed the problem. Also if its just faster to fix at your end that would be also great!

**Comment by sidkshatriya** [comment]
@robertoaloi Will greatly appreciate if you can have a look about ^

**Comment by robertoaloi** [comment]
Sure! Will fix!

**Comment by robertoaloi** [comment]
Fixed in #69
